### ISSUE TITLE
Please don't rotate my display without me

### ISSUE THREAD

**Issue by oxyii** [yoprogramo/QRcode_ST7735#1]
Unexpected side-effect after leaving screen with QR-code. Please remove this line

https://github.com/yoprogramo/QRcode_ST7735/blob/988db444fd97ecb41b71926bb6e9e31230eee98b/src/qrcode_st7735.cpp#L15

**Comment by oxyii** [comment]
I mean developer can rotate screen him-self if he wanna up->down render instead of left->right. It make sense to add this hack to readme. Anyway it would be more expected

P.S. Great job! Thank you for this useful lib

**Comment by yoprogramo** [comment]
> I mean developer can rotate screen him-self if he wanna up->down render instead of left->right. It make sense to add this hack to readme. Anyway it would be more expected
> 
> P.S. Great job! Thank you for this useful lib

Yeah! you are right. I'll try to make this user-selectable in the next version. The rotation is there to be able to adjust the offsets but I think I  can use the existing rotation for calculations.

**Comment by yoprogramo** [comment]
Modificatione done. Rotation removed for now.
